---
title: "Powerplantdata"
author: "Lauren Shohan"
date: "2024-11-11"
output: html_document
---

```{r setup, warning=F, error=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse);library(here);
library(sf);library(mapview);library(leaflet)
#library(arcgis)
here()
#love
```

Powerplant data Navigate to <https://www.nconemap.gov/> - NC's home for spatial data

```{r gas plants}
data_source <- paste0(
  'https://services.nconemap.gov/secure/rest/services/',
  'NC1Map_Hazardous_Waste/MapServer/4/',
  'query?outFields=*&where=1%3D1&f=geojson') #paste0 concantates strings for knit

gas_plants <- st_read(data_source)

mapview(gas_plants)

```

```{r read in powerplant data}
powerplants <- st_read('https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Plants_gdb/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson') %>% #mapview()
  filter(STATE == 'NC') %>%
  filter(TYPE != 'SOLAR PHOTOVOLTAIC') %>% 
  filter(TYPE!='CONVENTIONAL HYDROELECTRIC') %>%
  filter(TYPE!= 'BATTERIES; SOLAR PHOTOVOLTAIC')
```

```{r map power plant data}
#Create the map
cluster_map <- leaflet(powerplants) %>% 
  addTiles() %>% 
  addMarkers(
    #clusterOptions = markerClusterOptions(),
    popup = ~PRIM_FUEL
  )

cluster_map


```
