---
title: "Project"
author: "Lauren Shohan, Jessalyn Chuang, Alex López"
output: html_document
editor_options: 
  chunk_output_type: console
---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory

# Load your packages
library(tidyverse); library(lubridate); library(sf); library(leaflet)
library(mapview); library(leafsync); library(rvest); library(dataRetrieval);
library(here)
here()
# Set your ggplot theme

# Load your datasets


```


# Rationale and Research Questions



\newpage

# Dataset Information


```{r data.summary, echo = FALSE}
#table that summarizes data structure (variables, units, ranges and/or central
#tendencies, data source if multiple are used, etc.) - dont include code used 
#to generate the table

#kable(data, caption = , col.names = c(''), digits = )


```

\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
