---
title: "test"
output: html_document
date: "2024-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#hello
library(tidyverse);library(lubridate);library(here)
library(sf)
library(leaflet)
library(mapview)
library(rvest)
library(dataRetrieval)

here()
```

## R Markdown

```{r PM2.5 visualization}

#spatial visualization of 2014 PM2.5 data
pm2.5_2014 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2014.csv')) 

pm2.5_sf_2014 <- pm2.5_2014 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2014, zcol = 'meanPM')

#spatial visualization of 2015 PM2.5 data
pm2.5_2015 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2015.csv')) 

pm2.5_sf_2015 <- pm2.5_2015 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2015, zcol = 'meanPM')

#spatial visualization of 2016 PM2.5 data
pm2.5_2016 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2016.csv')) 

pm2.5_sf_2016 <- pm2.5_2016 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2016, zcol = 'meanPM')

#spatial visualization of 2022 PM2.5 data
pm2.5_2017 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2017.csv')) 

pm2.5_sf_2017 <- pm2.5_2017 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2017, zcol = 'meanPM')

#spatial visualization of 2018 PM2.5 data
pm2.5_2018 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2018.csv')) 

pm2.5_sf_2018 <- pm2.5_2018 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2018, zcol = 'meanPM')

#spatial visualization of 2019 PM2.5 data
pm2.5_2019 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2019.csv')) 

pm2.5_sf_2019 <- pm2.5_2019 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2019, zcol = 'meanPM')

#spatial visualization of 2020 PM2.5 data
pm2.5_2020 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2020.csv')) 

pm2.5_sf_2020 <- pm2.5_2020 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2020, zcol = 'meanPM')

#spatial visualization of 2021 PM2.5 data
pm2.5_2021 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2021.csv')) 

pm2.5_sf_2021 <- pm2.5_2021 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2021, zcol = 'meanPM')

#spatial visualization of 2022 PM2.5 data
pm2.5_2022 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2022.csv')) 

pm2.5_sf_2022 <- pm2.5_2022 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

mapview(pm2.5_sf_2022, zcol = 'meanPM')

#finding the two-year average in order to do analysis with EJ data

pm2.5_2013 <- read_csv(here('Data/EPA_PM2.5/EPA_PM25_NC2013.csv')) #we need 2013
#data for the 2-year average at 2014

pm2.5_sf_2013 <- pm2.5_2013 %>% 
  group_by(`Site ID`, County, `Site Latitude`, `Site Longitude`) %>% 
  summarize(
    meanPM = mean(`Daily Mean PM2.5 Concentration`,na.rm=T),
    maxPM = max(`Daily Mean PM2.5 Concentration`,na.rm=T)
    ) %>% 
  st_as_sf(coords = c('Site Longitude','Site Latitude'), crs=4269)

#combine spatial data frames for the 2-year averages
pm2.5_sf_20132014 <- rbind(pm2.5_sf_2013, pm2.5_sf_2014)

pm2.5_sf_20152016 <- rbind(pm2.5_sf_2015, pm2.5_sf_2016)

pm2.5_sf_20172018 <- rbind(pm2.5_sf_2017, pm2.5_sf_2018)

pm2.5_sf_20192020 <- rbind(pm2.5_sf_2019, pm2.5_sf_2020)

pm2.5_sf_20212022 <- rbind(pm2.5_sf_2021, pm2.5_sf_2022)

```

Powerplant data Navigate to <https://www.nconemap.gov/> - NC's home for spatial data

```{r gas plants}
data_source <- paste0(
  'https://services.nconemap.gov/secure/rest/services/',
  'NC1Map_Hazardous_Waste/MapServer/4/',
  'query?outFields=*&where=1%3D1&f=geojson') #paste0 concantates strings for knit

gas_plants <- st_read(data_source)

mapview(gas_plants)

```

```{r read in powerplant data}
powerplants <- st_read('https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Plants_gdb/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson') %>% #mapview()
 filter(STATE == 'NC') %>%
 filter(TYPE != 'SOLAR PHOTOVOLTAIC') %>% 
 filter(TYPE!='CONVENTIONAL HYDROELECTRIC') %>%
 filter(TYPE!= 'BATTERIES; SOLAR PHOTOVOLTAIC')
```

```{r map power plant data}
#Create the map
cluster_map <- leaflet(powerplants) %>% 
 addTiles() %>% 
 addMarkers(
 #clusterOptions = markerClusterOptions(),
 popup = ~PRIM_FUEL
 )

cluster_map
```

```{r wrangling CDC data}
library(sf)

#wrangling 2014 data because 2014 gdb import does not work
SVI2014_csv <- read.csv(here('Data/Project_Data/NorthCarolina_county_2014.csv'), 
                        colClasses = c('FIPS' = 'factor'))
NC_counties <- st_read(here('Data/Spatial/cb_2018_us_county_20m.shp')) %>% 
  filter(STATEFP == 37) %>% 
  rename(COUNTY = NAME)

SVI2014_gdb <- NC_counties %>% 
  left_join(
    SVI2014_csv, 
    by = c("GEOID" = "FIPS") 
    )

SVI2016_gdb <- st_read(here('Data/Project_Data/SVI2016_NORTHCAROLINA_COUNTY.gdb'))
SVI2018_gdb <- st_read(here('Data/Project_Data/SVI2018_NORTHCAROLINA_COUNTY.gdb'))
SVI2020_gdb <- st_read(here('Data/Project_Data/SVI2020_NORTHCAROLINA_COUNTY.gdb'))
SVI2022_gdb <- st_read(here('Data/Project_Data/SVI2022_NORTHCAROLINA_COUNTY.gdb'))

# Remove spatial information from SVI datasets
SVI2014_df <- SVI2014_gdb %>% st_drop_geometry() 
SVI2016_df <- SVI2016_gdb %>% st_drop_geometry()
SVI2018_df <- SVI2018_gdb %>% st_drop_geometry()
SVI2020_df <- SVI2020_gdb %>% st_drop_geometry()
SVI2022_df <- SVI2022_gdb %>% st_drop_geometry() 

#Renaming the GEOID column to FIPS to be able to join with other dataframes more 
#easily
SVI2014_df <- SVI2014_df %>%
  rename(FIPS = GEOID)

# Perform the joins on the selected columns for each of the themes to be able to 
#do GLM analysis for each theme
theme1 <- SVI2014_df %>%
  select(FIPS, RPL_THEME1) %>%
  inner_join(SVI2016_df %>% select(FIPS, RPL_THEME1), by = "FIPS") %>%
  inner_join(SVI2018_df %>% select(FIPS, RPL_THEME1), by = "FIPS") %>%
  inner_join(SVI2020_df %>% select(FIPS, RPL_THEME1), by = "FIPS") %>%
  inner_join(SVI2022_df %>% select(FIPS, RPL_THEME1), by = "FIPS")

colnames(theme1) <- c("FIPS", 2014, 2016, 2018, 2020, 2022)

theme2 <- SVI2014_df %>%
  select(FIPS, RPL_THEME1) %>%
  inner_join(SVI2016_df %>% select(FIPS, RPL_THEME2), by = "FIPS") %>%
  inner_join(SVI2018_df %>% select(FIPS, RPL_THEME2), by = "FIPS") %>%
  inner_join(SVI2020_df %>% select(FIPS, RPL_THEME2), by = "FIPS") %>%
  inner_join(SVI2022_df %>% select(FIPS, RPL_THEME2), by = "FIPS")

colnames(theme2) <- c("FIPS", 2014, 2016, 2018, 2020, 2022)

theme3 <- SVI2014_df %>%
  select(FIPS, RPL_THEME1) %>%
  inner_join(SVI2016_df %>% select(FIPS, RPL_THEME3), by = "FIPS") %>%
  inner_join(SVI2018_df %>% select(FIPS, RPL_THEME3), by = "FIPS") %>%
  inner_join(SVI2020_df %>% select(FIPS, RPL_THEME3), by = "FIPS") %>%
  inner_join(SVI2022_df %>% select(FIPS, RPL_THEME3), by = "FIPS")

colnames(theme3) <- c("FIPS", 2014, 2016, 2018, 2020, 2022)

theme4 <- SVI2014_df %>%
  select(FIPS, RPL_THEME1) %>%
  inner_join(SVI2016_df %>% select(FIPS, RPL_THEME4), by = "FIPS") %>%
  inner_join(SVI2018_df %>% select(FIPS, RPL_THEME4), by = "FIPS") %>%
  inner_join(SVI2020_df %>% select(FIPS, RPL_THEME4), by = "FIPS") %>%
  inner_join(SVI2022_df %>% select(FIPS, RPL_THEME4), by = "FIPS")

colnames(theme4) <- c("FIPS", 2014, 2016, 2018, 2020, 2022)

#mapview(SVI2018_gdb, zcol = "RPL_THEME1") + mapview(powerplants, col.regions = "black") + mapview(pm2.5_sf, cex = "meanPM")

```